### ISSUE TITLE
Nightly audit report for BC Registries Audit (prod)

### ISSUE THREAD

**Issue by schaturv18** [bcgov/von-bc-registries-agent#384]
As per the nightly report below

Corp Type mis-match for: FM0360774; BC Reg: "GP", OrgBook: "LP"
Corp Type mis-match for: FM0073945; BC Reg: "SP", OrgBook: "LP"
Business Number mis-match for: FM0862412 BC Reg: "798226106", OrgBook: ""

Can you please update FM0360774 and FM0073945 as LP to match our system?
Also please update BN for FM0862412 as it is correctly showing this BN in our system?

**Comment by WadeBarnes** [comment]
@schaturv18, I've been meaning to ask about `FM0862412`.  There seems to be something "off" about the records for it.  I've tried reprocessing it in several ways but the BN does not come through from LEAR.  Would you be able to look into this for us?

For example, every other BN mismatch for COLIN and LEAR are generally fixed by an automated SQL process which is run by the audit when a mismatch is detected.  In the very odd cases the automated fix does not work we're able to reprocess the corp records and the BN syncs.  With `FM0862412` neither of these processes are working which indicates there's some anomaly with the records for that corp in LEAR.

**Comment by WadeBarnes** [comment]
@schaturv18, As for `FM0073945` and `FM0360774`, their records match the records in COLIN, as we've been told they should.  The state you're referring to is their state in LEAR, which we've been told were entered there by mistake and are being retained for historical purposes.  If you look at the most recent audit reports from LEAR, you'll see they have been added to an ignore list.

**Comment by WadeBarnes** [comment]
@schaturv18, The related PR; https://github.com/bcgov/von-bc-registries-audit/pull/53

**Comment by schaturv18** [comment]
For FM0862412, we have BN in both legacy as well as lear. Can you please share the SQL that checks for the BN for this report?

**Comment by swcurran** [comment]
I'd suggest that we meet to discuss this vs. messaging. It's a confusing issue and will take some back and forth to define the best approach.

**Comment by WadeBarnes** [comment]
For completeness ...

I believe this is the SQL used to fetch the corp info from LEAR including the BN:
- https://github.com/bcgov/von-bc-registries-agent/blob/main/data-pipeline/bcreg/bcreg_lear.py#L658-L677

And this is where the BN credential gets generated:
- https://github.com/bcgov/von-bc-registries-agent/blob/main/data-pipeline/bcreg/eventprocessor.py#L1249-L1263

**Comment by WadeBarnes** [comment]
Example of corps in LEAR who's BN's was automatically fixed by the LEAR audit for comparison to `FM0862412`:
- FM1082730
- FM1085856
- FM1034633
- FM1079134

The BN mismatch for these corps was automatically fixed by the audit script 2025-Sept-10 when initially detected.  `FM0862412` was included in the same SQL statement that was used to fix the other records, but the BN for `FM0862412` was not updated like the others.

**Comment by WadeBarnes** [comment]
Report of BN mismatch for `FM0862412` started 2025-Aug-27.  The audit report for 2025-Aug-26 had no indication of a BN mismatch.

**Comment by WadeBarnes** [comment]
Interestingly enough the BN `798226106` is associated with the parent company of `FM0862412`; `A0120074` - [NOVA BUS INC.](https://orgbook.gov.bc.ca/entity/A0120074/type/registration.registries.ca)

**Comment by WadeBarnes** [comment]
Here is an example of how the OrgBook manages the BN for a parent and it's child corps when the BN's are registered with both; BN-9 coming from the parent corp.

[TELUS COMMUNICATIONS INC.](https://orgbook.gov.bc.ca/entity/BC1101218/type/registration.registries.ca)
- Related Sole Props found by searching for the BN `100652692`; https://orgbook.gov.bc.ca/search?q=100652692&category%3Aentity_type=&credential_type_id=&inactive=&page=1

**Comment by WadeBarnes** [comment]
Additional data points.  The LEAR audit this morning identified 13 BN mismatches (missing BNs) in the OrgBook.  The script applied its auto-fix to all 13.  All of the BNs _except_ than the one for `FM0862412` (Nova Bus) were updated as expected.

- FM1085938
- FM1085941
- FM1085939
- FM1085942
- FM1085955
- FM1085894
- FM1085860
- FM1085940
- FM1082758
- FM1085937
- `FM0862412`
- FM1084524
- FM1086387

**Comment by JaySharpgov** [comment]
Im going to email CRA as they are showing the parent for FM0862412, A0120074 as being inactive. which doesnt match what we have. That MAY be a blockage on this. But either way the BN of 798226106BC0002 should be added to the orgbook data.

**Comment by WadeBarnes** [comment]
@JaySharpgov, Thanks for the update.  We had a meeting with Siddharth and Michael on Wednesday.  They are looking into the records for FM0862412 to see if they can determine why the BN does not come through when we process the records.  We've provided a number of examples of other corp records where this is not a problem.

**Comment by JaySharpgov** [comment]
ok so CRA replied back stating that the BN and expro corp are active on their side. It looks like just BNI has it as inactive. So BNI needs to be updated.

**Comment by WadeBarnes** [comment]
@JaySharpgov, Please post a note here when that is done.  That way we'll know to watch for the issue to, potentially, resolve on it's own on the OrgBook side.

**Comment by JaySharpgov** [comment]
i think @schaturv18 might have to do that part. I'm not sure my team can outright update BNI.

**Comment by WadeBarnes** [comment]
All good.  Either way, let us know here.

**Comment by JaySharpgov** [comment]
BNI Updated to make parent active. Thanks @schaturv18

**Comment by WadeBarnes** [comment]
Thanks.  I'll keep an eye out tomorrow morning and report back.

**Comment by WadeBarnes** [comment]
@JaySharpgov, @schaturv18, There were a number of missing BNs included in both the COLIN and LEAR audit this morning.  All of them expect for the BN for FM0862412 were automatically fixed by the scripts.

Included were:

COLIN:
- BC1558145
- BC1557964

LEAR:
- FM1085957
- FM1059858 
- FM1081584
- FM1084399 
- FM1026374 
- FM1076750 
- FM0862412 - Missing BN was not fixed like all the others.

This indicates further investigation into the data for FM0862412 is required.

**Comment by schaturv18** [comment]
I just wanted to back on this one. I believe FM0862412 is still not fixed.

**Comment by WadeBarnes** [comment]
You are correct.  We are still awaiting feedback regarding the deeper investigation into the records for this company.  It's the only one with this particular issue, all other BN adjustments in both COLIN and LEAR for all other companies have been processed successfully, indicating further investigation into the data for FM0862412 is required.

**Comment by WadeBarnes** [comment]
Connectivity information:
- The BC Registries Agent is getting it's data feed from the following databases:
  - `prod`: business database hosted in `d2b3d8-prod` (Gold Cluster) - **This is the connection for the topic of this ticket.**
  - `test`:  business database hosted in `d2b3d8-test` (Gold Cluster)
  - `dev`:  business database hosted in `d2b3d8-dev` (Gold Cluster)

@pwei1018 was the one that setup these backup databases and the connections we're using.

Would it be possible to coordinate with the LEAR team to confirm whether the data for `FM0862412` in the backup database matches the data in the live database in GCP?

**Comment by schaturv18** [comment]
Hi Wade,

I can confirm that the data in prod database hosted on d2b3d8-prod is correct.

<img width="691" height="336" alt="Image" src="https://github.com/user-attachments/assets/80fe0926-4e5e-4b55-a83e-21353d802735" />

**Comment by esune** [comment]
Added relevant corps to the ignore list as interim fix.
